spring           :
    data      :
        mongodb:
            host: 172.20.1.6
            port: 27017
            database: medical
    datasource:
        url              : jdbc:postgresql://172.20.1.6:5432/postgres
#        type             : org.apache.ibatis.datasource.pooled.PooledDataSource
        username         : root
        password         : root
#        driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
    ru.relex.techtalks: warn
#    root: info
#    root: debug
