spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: medical
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: root
    password: root
logging:
  level:
    root: info
    ru.relex.techtalks: warn
#    root: info
#    root: debug
